/*
 * protocolo.h
 *
 *  Created on: 16/9/2017
 *      Author: utnso
 */

#ifndef PROTOCOLO_H_
#define PROTOCOLO_H_

/* IDS DE LOS PROCESOS */
#define PROCESO_NODO 1
#define PROCESO_FILESYSTEM 2
#define PROCESO_YAMA 3
#define PROCESO_MASTER 4


/* PROTOCOLO MENSAJES */
#define ENVIAR_ARCHIVO_TEXTO 20
#define ACCION_PROCESAR_ARCHIVO 21
#define ACCION_PROCESAR_TRANSFORMACION 22
#define TRANSFORMAR_ARCHIVO 23
#define REDUCIR_ARCHIVO 24
#define ACCION_PROCESAR_REDUCCION_LOCAL 25
#define ACCION_PROCESAR_REDUCCION_GLOBAL 26
#define ACCION_PROCESAR_ALMACENADO_FINAL 27
#define RESULTADO_TRANSFORMACION 28
#define RESULTADO_REDUCCION_LOCAL 29
#define RESULTADO_REDUCCION_GLOBAL 30
#define RESULTADO_ALMACENADO_FINAL 31
#define ACCION_TRANSFORMACION 32
#define ACCION_REDUCCION_LOCAL 33
#define ACCION_REDUCCION_GLOBAL 34



#endif /* PROTOCOLO_H_ */
