/*
 * protocolo.h
 *
 *  Created on: 16/9/2017
 *      Author: utnso
 */

#ifndef PROTOCOLO_H_
#define PROTOCOLO_H_

/* IDS DE LOS PROCESOS */
#define PROCESO_NODO 1
#define PROCESO_FILESYSTEM 2
#define PROCESO_YAMA 3
#define PROCESO_MASTER 4
#define PROCESO_WORKER 5


/* PROTOCOLO MENSAJES */
#define TRANSFORMACION_OK 16
#define REDUCCION_LOCAL_OK 17
#define REDUCCION_GLOBAL_OK 18
#define ENVIAR_ARCHIVO_BINARIO 19
#define ENVIAR_ARCHIVO_TEXTO 20
#define ACCION_PROCESAR_ARCHIVO 21
#define ACCION_PROCESAR_TRANSFORMACION 22
#define ACCION_PROCESAR_REDUCCION_LOCAL 23
#define ACCION_PROCESAR_REDUCCION_GLOBAL 24
#define ACCION_PROCESAR_ALMACENADO_FINAL 25
#define RESULTADO_TRANSFORMACION 26
#define RESULTADO_REDUCCION_LOCAL 27
#define RESULTADO_REDUCCION_GLOBAL 28
#define RESULTADO_ALMACENADO_FINAL 29
#define ACCION_TRANSFORMACION 30
#define ACCION_REDUCCION_LOCAL 31
#define ACCION_REDUCCION_GLOBAL 32
#define COMENZAR_REDUCCION_GLOBAL 33
#define ACCION_RECIBIR_PALABRA 34
#define ESCRIBIR_BLOQUE_NODO 35
#define LEER_BLOQUE_NODO 36
#define ENVIAR_PROGRAMA_TRANSFORMACION 37
#define TRANSFORMACION_ERROR 38
#define REDUCCION_LOCAL_ERROR 39
#define REDUCCION_GLOBAL_ERROR 40
#define ACCION_ALMACENAMIENTO_FINAL 41
#define CONTINUAR_ENVIO 42
#define TRANSFORMACION_ERROR_CREACION 43
#define TRANSFORMACION_ERROR_ESCRITURA 44
#define TRANSFORMACION_ERROR_PERMISOS 45
#define REDUCCION_LOCAL_ERROR_CREACION 46
#define REDUCCION_LOCAL_ERROR_ESCRITURA 47
#define REDUCCION_LOCAL_ERROR_PERMISOS 48
#define REDUCCION_GLOBAL_ERROR_CREACION 49
#define REDUCCION_GLOBAL_ERROR_ESCRITURA 50
#define REDUCCION_GLOBAL_ERROR_PERMISOS 51
#define REDUCCION_LOCAL_ERROR_SYSTEM 52
#define REDUCCION_GLOBAL_ERROR_APAREO 53
#define REDUCCION_GLOBAL_ERROR_SYSTEM 54


#endif /* PROTOCOLO_H_ */
