/*
 * protocolo.h
 *
 *  Created on: 16/9/2017
 *      Author: utnso
 */

#ifndef PROTOCOLO_H_
#define PROTOCOLO_H_

/* IDS DE LOS PROCESOS */
#define PROCESO_NODO 1
#define PROCESO_FILESYSTEM 2
#define PROCESO_YAMA 3
#define PROCESO_MASTER 4
#define PROCESO_WORKER 5


/* PROTOCOLO MENSAJES */
#define ENVIAR_ARCHIVO_BINARIO 19
#define ENVIAR_ARCHIVO_TEXTO 20
#define ACCION_PROCESAR_ARCHIVO 21
#define ACCION_PROCESAR_TRANSFORMACION 22
#define ACCION_PROCESAR_REDUCCION_LOCAL 23
#define ACCION_PROCESAR_REDUCCION_GLOBAL 24
#define ACCION_PROCESAR_ALMACENADO_FINAL 25
#define RESULTADO_TRANSFORMACION 26
#define RESULTADO_REDUCCION_LOCAL 27
#define RESULTADO_REDUCCION_GLOBAL 28
#define RESULTADO_ALMACENADO_FINAL 29
#define ACCION_TRANSFORMACION 30
#define ACCION_REDUCCION_LOCAL 31
#define ACCION_REDUCCION_GLOBAL 32
#define ACCION_ENVIAR_ARCHIVO_TEMP_DE_RL 33
#define ACCION_LEER_ARCHIVO_TEMP_DE_RL 34
#define ESCRIBIR_BLOQUE_NODO 35
#define LEER_BLOQUE_NODO 36
#define ENVIAR_PROGRAMA_TRANSFORMACION 37



#endif /* PROTOCOLO_H_ */
